ingress:
  enabled: true
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: ""
  hosts:
    - host: ""
      paths:
        - path: /*,
          backend:
            serviceName: broker,
            servicePort: 1026
    - host: ""
      paths:
        - path: /*,
          backend:
            serviceName: wirecloud,
            servicePort: 80

autoscaling:
  enabled: true

orionDeploy:
  env:
    ORION_MONGO_HOST: ""
    ORION_MONGO_USER: ""
    ORION_MONGO_PASSWORD: ""
    ORION_MONGO_DB: ""

wirecloudDeploy:
  env:
    DB_HOST: ""
    DB_USERNAME: ""
    DB_PASSWORD: ""
