---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: polder
  region: eu-central-1

managedNodeGroups:
  - name: "ng-small"
    instanceTypes: ["t3.small", "t2.small", "t3a.small"]
    desiredCapacity: 2
    maxSize: 5
    spot: true
