apiVersion: apps/v1
kind: Deployment
metadata:
  name: draco
  labels:
    app: draco
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      app: draco
  template:
    metadata:
      labels:
        app: draco
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: draco
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.dracoDeploy.repository }}:{{ .Values.dracoDeploy.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.dracoDeploy.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.dracoDeploy.containerPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.dracoResources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
