apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.keyrockService.name }}
  labels:
    {{- include "polder.labels" . | nindent 4 }}
spec:
  type: {{ .Values.keyrockService.type }}
  ports:
    - port: {{ .Values.keyrockService.port }}
      targetPort: {{ .Values.keyrockDeploy.containerPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "polder.selectorLabels" . | nindent 4 }}
    app: keyrock
