apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.orionService.name }}
  labels:
    {{- include "polder.labels" . | nindent 4 }}
spec:
  type: {{ .Values.orionService.type }}
  ports:
    - port: {{ .Values.orionService.port }}
      targetPort: {{ .Values.orionDeploy.containerPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "polder.selectorLabels" . | nindent 4 }}
    app: broker
