apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
  labels:
    {{- include "polder.labels" . | nindent 4 }}
    app: broker
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "polder.selectorLabels" . | nindent 6 }}
      app: broker
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "polder.labels" . | nindent 8 }}
        app: broker
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.orionDeploy.repository }}:{{ .Values.orionDeploy.tag }}"
          imagePullPolicy: {{ .Values.orionDeploy.pullPolicy }}
          env:
            {{- range $key, $val := .Values.orionDeploy.env}}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end}}
          ports:
            - name: http
              containerPort: {{ .Values.orionDeploy.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /v2/entities
              port: {{ .Values.orionDeploy.containerPort }}
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /v2/entities
              port: {{ .Values.orionDeploy.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.orionResources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
