apiVersion: apps/v1
kind: Deployment
metadata:
  name: wilma
  labels:
    {{- include "polder.labels" . | nindent 4 }}
    app: wilma
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "polder.selectorLabels" . | nindent 6 }}
      app: wilma
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "polder.labels" . | nindent 8 }}
        app: wilma
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.wilmaDeploy.repository }}:{{ .Values.wilmaDeploy.tag }}"
          imagePullPolicy: {{ .Values.wilmaDeploy.pullPolicy }}
          env:
            {{- range $key, $val := .Values.wilmaDeploy.env}}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end}}
          ports:
            - name: http
              containerPort: {{ .Values.wilmaDeploy.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.wilmaDeploy.env.PEP_PROXY_PUBLIC_PATHS }}
              port: {{ .Values.wilmaDeploy.containerPort }}
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: {{ .Values.wilmaDeploy.env.PEP_PROXY_PUBLIC_PATHS }}
              port: {{ .Values.wilmaDeploy.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.wilmaResources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
