{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata: 
  name: wirecloud-scaler
  labels:
    {{- include "polder.labels" . | nindent 4 }}
    app: wirecloud
spec: 
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  scaleTargetRef: 
    apiVersion: apps/v1 
    kind: Deployment
    name: wirecloud
  metrics: 
  - type: Resource
    resource: 
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource: 
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
