apiVersion: apps/v1
kind: Deployment
metadata:
  name: wirecloud
  labels:
    {{- include "polder.labels" . | nindent 4 }}
    app: wirecloud
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "polder.selectorLabels" . | nindent 6 }}
      app: wirecloud
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "polder.labels" . | nindent 8 }}
        app: wirecloud
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: static-files
          emptyDir: {}
        - name: wirecloud-data
          persistentVolumeClaim:
            claimName: wirecloud-widget-claim
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
      containers:
        - name: nginx
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: nginx
          imagePullPolicy: {{ .Values.wirecloudDeploy.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.wirecloudDeploy.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.wirecloudDeploy.containerPort }}
            initialDelaySeconds: 25
            periodSeconds: 20
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.wirecloudDeploy.containerPort }}
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 10
          resources:
            {{- toYaml .Values.wirecloudResources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              readOnly: true
              name: nginx-conf
              subPath: nginx.conf
            - mountPath: /var/www/static
              name: static-files
        - name: wirecloud
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.wirecloudDeploy.repository }}:{{ .Values.wirecloudDeploy.tag  }}"
          imagePullPolicy: {{ .Values.wirecloudDeploy.pullPolicy }}
          env:
            {{- range $key, $val := .Values.wirecloudDeploy.env}}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end}}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /login
              port: 8000
            initialDelaySeconds: 25
            periodSeconds: 20
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /login
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 10
          resources:
            {{- toYaml .Values.wirecloudResources | nindent 12 }}
          volumeMounts:
            - mountPath: /var/www/static
              name: static-files
            - mountPath: /opt/wirecloud_instance/data
              name: wirecloud-data
              subPath: wirecloud-data
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
